"""initial schema

Revision ID: 4dc355121299
Revises: 
Create Date: 2026-09-30 21:27:16.297563
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4dc355121299'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dinner_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.String(length=128), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('initiator_id', sa.String(length=128), nullable=False),
    sa.Column('initiator_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('suggested_time', sa.String(length=255), nullable=True),
    sa.Column('deadline', sa.String(length=255), nullable=True),
    sa.Column('confirmed_plan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dinner_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dinner_activities_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dinner_activities_status'), ['status'], unique=False)

    op.create_table('inbound_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wecom_msg_id', sa.String(length=128), nullable=False),
    sa.Column('group_id', sa.String(length=128), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('sender_id', sa.String(length=128), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('msg_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbound_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbound_messages_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_messages_wecom_msg_id'), ['wecom_msg_id'], unique=True)

    op.create_table('activity_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('available_time', sa.String(length=255), nullable=True),
    sa.Column('cuisine_preference', sa.String(length=255), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['dinner_activities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'user_id', name='uq_activity_participant')
    )
    with op.batch_alter_table('activity_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_participants_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_participants_user_id'), ['user_id'], unique=False)

    op.create_table('dinner_proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('proposed_time', sa.String(length=255), nullable=False),
    sa.Column('cuisine', sa.String(length=255), nullable=False),
    sa.Column('budget_estimate', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['dinner_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dinner_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dinner_proposals_activity_id'), ['activity_id'], unique=False)

    op.create_table('outbox_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['dinner_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_messages_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_messages_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_messages_status'), ['status'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['dinner_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_reminder_type'), ['reminder_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_status'), ['status'], unique=False)

    op.create_table('votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['dinner_activities.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['dinner_proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'user_id', name='uq_activity_vote')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_votes_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_votes_proposal_id'), ['proposal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_votes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_votes_user_id'))
        batch_op.drop_index(batch_op.f('ix_votes_proposal_id'))
        batch_op.drop_index(batch_op.f('ix_votes_activity_id'))

    op.drop_table('votes')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_status'))
        batch_op.drop_index(batch_op.f('ix_reminders_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_reminders_reminder_type'))
        batch_op.drop_index(batch_op.f('ix_reminders_activity_id'))

    op.drop_table('reminders')
    with op.batch_alter_table('outbox_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_messages_status'))
        batch_op.drop_index(batch_op.f('ix_outbox_messages_group_id'))
        batch_op.drop_index(batch_op.f('ix_outbox_messages_activity_id'))

    op.drop_table('outbox_messages')
    with op.batch_alter_table('dinner_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dinner_proposals_activity_id'))

    op.drop_table('dinner_proposals')
    with op.batch_alter_table('activity_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_participants_activity_id'))

    op.drop_table('activity_participants')
    with op.batch_alter_table('inbound_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbound_messages_wecom_msg_id'))
        batch_op.drop_index(batch_op.f('ix_inbound_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_inbound_messages_group_id'))

    op.drop_table('inbound_messages')
    with op.batch_alter_table('dinner_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dinner_activities_status'))
        batch_op.drop_index(batch_op.f('ix_dinner_activities_group_id'))

    op.drop_table('dinner_activities')
    # ### end Alembic commands ###
